sudo: false
language: java
jdk:
  - oraclejdk8

# https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766
dist: trusty

cache:
  directories:
    - $HOME/.m2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/13ca3dd0f0bbc821ff55
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
  - pip install --user codecov
after_success:
  - mvn validate -e
  - codecov

